language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - redis-server
# command to install dependencies
install:
  - pip install codecov
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run test.py

# Push the results back to codecov
after_success:
  - codecov